function ui_FigPropPanel(propPanel, panelSize)
    
    uipos_typePanelH = 100;
    uipos_axisPanelH = 220;
    
    
    height1 = uipos_axisPanelH + uipos_typePanelH;
    
    uipos_otherPanelH = panelSize(2) - height1 - 10;
    
    GraphType = uibuttongroup(propPanel,...
        'Title','Graph type',...
        'Units','pixels',...
        'Position',[0 panelSize(2)-uipos_typePanelH panelSize(1) uipos_typePanelH]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Histogram',...
        'Position',[5 55 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Dot Plot',...
        'Position',[5 30 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Colored Dot Plot',...
        'Position',[panelSize(1)/2-20 30 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Contour',...
        'Position',[5 5 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Filled Contour',...
        'Position',[panelSize(1)/2-20 5 95,20]);
    
    
    AxisProp = uibuttongroup(propPanel,...
        'Title','Axis settings',...
        'Units','pixels',...
        'Position',[0 panelSize(2)-height1-5 panelSize(1) uipos_axisPanelH]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Linear', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-50 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Logarithmic', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-70 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Hyperbolic', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-90 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Logicle', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-110 60 20]);
    
    
    Xaxis=uibuttongroup(AxisProp,...
        'Title','X-axis',...
        'Units','pixels',...
        'Position',[85 uipos_axisPanelH-110 35 97]);
    uicontrol(Xaxis,...
        'Style','Radio',...
        'Tag','lin',...
        'UserData',[0 Inf 1],...
        'Position',[5 62 35 20]);
    uicontrol(Xaxis,...
        'Style','Radio',...
        'Tag','log',...
        'UserData',[0 Inf 1],...
        'Position',[5 42 35 20]);
    uicontrol(Xaxis,...
        'Style','Radio',...
        'Tag','logicle',...
        'UserData',[-Inf Inf 1],...
        'Position',[5 22 35 20]);
    uicontrol(Xaxis,...
        'Style','Radio',...
        'Tag','logicle',...
        'UserData',[-Inf Inf 10^-1.6],...
        'Position',[5 2 35 20]);
    
    Yaxis=uibuttongroup(AxisProp,...
        'Title','Y-axis',...
        'Units','pixels',...
        'Position',[145 uipos_axisPanelH-110 35 97]);
    uicontrol(Yaxis,...
        'Style','Radio',...
        'Tag','lin',...
        'UserData',[0 Inf 1],...
        'Position',[5 62 35 20]);
    uicontrol(Yaxis,...
        'Style','Radio',...
        'Tag','log',...
        'UserData',[0 Inf 1],...
        'Position',[5 42 35 20]);
    uicontrol(Yaxis,...
        'Style','Radio',...
        'Tag','logicle',...
        'UserData',[-Inf Inf 1],...
        'Position',[5 22 35 20]);
    uicontrol(Yaxis,...
        'Style','Radio',...
        'Tag','logicle',...
        'UserData',[-Inf Inf 10^-1.6],...
        'Position',[5 2 35 20]);
    
    uicontrol(AxisProp,...
        'Style','Text', 'String','MIN =', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-145 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','MAX =', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-170 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','PRM =', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-195 60 20]);

    uicontrol(AxisProp,...
        'Style','checkbox',...
        'Position',[85 5 180 20],...
        'String','Auto axis',...
        'Value',1,...
        'Tag','AutoXAxis',...
        'Callback',{@XAutoCallback});

    Xparam(1)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Min',...
        'Position',[85 uipos_axisPanelH-140 48 20],...
        'Enable','off',...
        'Callback',{@XparamCallback});
    Xparam(2)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Max',...
        'Position',[85 uipos_axisPanelH-165 48 20],...
        'Enable','off',...
        'Callback',{@XparamCallback});
    Xparam(3)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Prm',...
        'Position',[85 uipos_axisPanelH-190 48 20],...
        'Enable','off',...
        'Callback',{@XparamCallback});
    
    Yparam(1)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Min',...
        'Position',[145 uipos_axisPanelH-140 48 20],...
        'Enable','off',...
        'Callback',{@YparamCallback});
    Yparam(2)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Max',...
        'Position',[145 uipos_axisPanelH-165 48 20],...
        'Enable','off',...
        'Callback',{@YparamCallback});
    Yparam(3)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Prm',...
        'Position',[145 uipos_axisPanelH-190 48 20],...
        'Enable','off',...
        'Callback',{@YparamCallback});
    
    Yprmhist=uibuttongroup(propPanel,...
        'Title','Histogram settings',...
        'Units','pixels',...
        'Position',[0 0 panelSize(1) uipos_otherPanelH],...
        'SelectionChangeFcn',{@YprmhistCallback});
    uicontrol(Yprmhist,...
        'Style','Text',...
        'Position',[30 uipos_otherPanelH-40 90 20],...
        'String','Normalize area to:');
    uicontrol(Yprmhist,...
        'Style','Radio','Position',[35 uipos_otherPanelH-55 30 20],'String','1','Tag','Total','Value',1);
    uicontrol(Yprmhist,...
        'Style','Radio','Position',[75 uipos_otherPanelH-55 30 20],'String','%','Tag','Gated');
    uicontrol(Yprmhist,...
        'Style','Radio','Position',[115 uipos_otherPanelH-55 30 20],'String','#','Tag','Abs');
    
    uicontrol(Yprmhist,...
        'Style','Text','Position',[30 7 60 20],'String','Smoothing:','HorizontalAlignment','left');
    uicontrol(Yprmhist,...
        'Style','Edit','Position',[90 10 30 20],'String','1','Tag','smoothprm','Enable','on','BackgroundColor',[1 1 1],'Callback',@SmoothCallback);
    
    
    function XAutoCallback(varargin)
    end
    
    function XparamCallback(varargin)
    end

    function YprmhistCallback(varargin)
    end
    
end