function ui_FigPropPanel(efdb, propPanel, panelSize)
    
    uipos_typePanelH = 100;
    uipos_axisPanelH = 220;
    height1 = uipos_axisPanelH + uipos_typePanelH;
    uipos_otherPanelH = panelSize(2) - height1 - 10;
    
    GraphType = uibuttongroup(propPanel,...
        'Title','Graph type',...
        'Units','pixels',...
        'SelectionChangeFcn',@GraphTypeSelCh,...
        'Position',[0 panelSize(2)-uipos_typePanelH panelSize(1) uipos_typePanelH]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Histogram',...
        'Position',[5 55 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Dot Plot',...
        'Position',[5 30 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Colored Dot Plot',...
        'Position',[panelSize(1)/2-20 30 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Contour',...
        'Position',[5 5 95,20]);
    uicontrol(GraphType,...
        'Style','Radio',...
        'String','Filled Contour',...
        'Position',[panelSize(1)/2-20 5 95,20]);
    
    set(GraphType,'SelectedObject',getcolumn(get(GraphType,'Children')',efdb.Display.graph_type_Radio));
    
    
    AxisProp = uibuttongroup(propPanel,...
        'Title','Axis settings',...
        'Units','pixels',...
        'Position',[0 panelSize(2)-height1-5 panelSize(1) uipos_axisPanelH]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Linear', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-50 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Logarithmic', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-70 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Hyperbolic', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-90 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','Logicle', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-110 60 20]);
    
    
    XaxisBG=uibuttongroup(AxisProp,...
        'Title','X-axis','Units','pixels',...
        'SelectionChangeFcn',@XaxisSelCh,...
        'Position',[85 uipos_axisPanelH-110 35 97]);
    Xaxis(1) = uicontrol(XaxisBG,...
        'Style','Radio','Tag','lin','Enable','on',...
        'UserData',[0 Inf 1],...
        'Position',[5 62 35 20]);
    Xaxis(2) = uicontrol(XaxisBG,...
        'Style','Radio','Tag','log', 'Enable', 'on',...
        'UserData',[0 Inf 1],...
        'Position',[5 42 35 20]);
    Xaxis(3) = uicontrol(XaxisBG,...
        'Style','Radio','Tag','logicle', 'Enable', 'on',...
        'UserData',[-Inf Inf 1],...
        'Position',[5 22 35 20]);
    Xaxis(4) = uicontrol(XaxisBG,...
        'Style','Radio','Tag','logicle', 'Enable', 'on',...
        'UserData',[-Inf Inf 10^-1.6],...
        'Position',[5 2 35 20]);
    
    set(XaxisBG,'SelectedObject',getcolumn(get(XaxisBG,'Children')',efdb.Display.graph_Xaxis_Radio));

    
    YaxisBG=uibuttongroup(AxisProp,...
        'Title','Y-axis',...
        'Units','pixels',...
        'SelectionChangeFcn',@YaxisSelCh,...
        'Position',[145 uipos_axisPanelH-110 35 97]);
    Yaxis(1) = uicontrol(YaxisBG,...
        'Style','Radio','Tag','lin',...
        'UserData',[0 Inf 1], 'Enable', 'off',...
        'Position',[5 62 35 20]);
    Yaxis(2) = uicontrol(YaxisBG,...
        'Style','Radio','Tag','log',...
        'UserData',[0 Inf 1], 'Enable', 'off',...
        'Position',[5 42 35 20]);
    Yaxis(3) = uicontrol(YaxisBG,...
        'Style','Radio','Tag','logicle',...
        'UserData',[-Inf Inf 1], 'Enable', 'off',...
        'Position',[5 22 35 20]);
    Yaxis(4) = uicontrol(YaxisBG,...
        'Style','Radio','Tag','logicle',...
        'UserData',[-Inf Inf 10^-1.6], 'Enable', 'off',...
        'Position',[5 2 35 20]);
    set(YaxisBG,'SelectedObject',getcolumn(get(YaxisBG,'Children')',efdb.Display.graph_Yaxis_Radio));

    
    uicontrol(AxisProp,...
        'Style','Text', 'String','MIN =', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-145 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','MAX =', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-170 60 20]);
    uicontrol(AxisProp,...
        'Style','Text', 'String','PRM =', 'HorizontalAlignment','right', 'Position',[5 uipos_axisPanelH-195 60 20]);

    Xauto = uicontrol(AxisProp,...
        'Style','checkbox','Position',[85 5 180 20],...
        'String','Auto-X','Value',1,...
        'Tag','AutoXAxis',...
        'Callback',{@XAutoCallback});
    
    Yauto = uicontrol(AxisProp,...
        'Style','checkbox','Position',[145 5 180 20],...
        'String','Auto-Y','Value',1,'Enable','off',...
        'Tag','AutoXAxis',...
        'Callback',{@YAutoCallback});

    Xparam(1)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Min',...
        'Position',[85 uipos_axisPanelH-140 48 20],...
        'Enable','off',...
        'Callback',{@XparamCallback});
    Xparam(2)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Max',...
        'Position',[85 uipos_axisPanelH-165 48 20],...
        'Enable','off',...
        'Callback',{@XparamCallback});
    Xparam(3)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Prm',...
        'Position',[85 uipos_axisPanelH-190 48 20],...
        'Enable','off',...
        'Callback',{@XparamCallback});
    
    Yparam(1)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Min',...
        'Position',[145 uipos_axisPanelH-140 48 20],...
        'Enable','off',...
        'Callback',{@YparamCallback});
    Yparam(2)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Max',...
        'Position',[145 uipos_axisPanelH-165 48 20],...
        'Enable','off',...
        'Callback',{@YparamCallback});
    Yparam(3)=uicontrol(AxisProp,...
        'Style','Edit',...
        'String','Prm',...
        'Position',[145 uipos_axisPanelH-190 48 20],...
        'Enable','off',...
        'Callback',{@YparamCallback});
    
    YprmhistBG=uibuttongroup(propPanel,...
        'Title','Histogram settings',...
        'Units','pixels',...
        'Position',[0 0 panelSize(1) uipos_otherPanelH],...
        'SelectionChangeFcn',{@YprmhistCallback});
    uicontrol(YprmhistBG,...
        'Style','Text',...
        'Position',[30 uipos_otherPanelH-40 90 20],...
        'String','Normalize area to:');
    Yprmhist(1) = uicontrol(YprmhistBG,...
        'Style','Radio','Position',[35 uipos_otherPanelH-55 30 20],'String','1','Tag','Total','Value',1);
    Yprmhist(2) = uicontrol(YprmhistBG,...
        'Style','Radio','Position',[75 uipos_otherPanelH-55 30 20],'String','%','Tag','Gated');
    Yprmhist(3) = uicontrol(YprmhistBG,...
        'Style','Radio','Position',[115 uipos_otherPanelH-55 30 20],'String','#','Tag','Abs');
    
    uicontrol(YprmhistBG,...
        'Style','Text','Position',[30 7 60 20],'String','Smoothing:','HorizontalAlignment','left');
    Yprmhist(4) = uicontrol(YprmhistBG,...
        'Style','Edit','Position',[90 10 30 20],'String','1','Tag','smoothprm','Enable','on','BackgroundColor',[1 1 1],'Callback',@SmoothCallback);
    
    
    function GraphTypeSelCh(hObject,eventdata)
        mArgsIn=guidata(hObject);
        hMainFig=mArgsIn.Handles.fh;
        
        mArgsIn.Display.Changed=1;
        mArgsIn.Display.graph_type=get(get(hObject,'SelectedObject'),'String');
        mArgsIn.Display.graph_type_Radio=find(get(hObject,'Children')==get(hObject,'SelectedObject'));
        
        guidata(hMainFig,mArgsIn);
%         Args=guidata(mArgsIn.Handles.graphprop);
        
        if strcmp(mArgsIn.Display.graph_type,'Histogram')
            set([Yparam,Yaxis,Yauto], 'Enable','off');
            set(Yprmhist,'Enable','on');
        else
            set([Yparam,Yaxis,Yauto], 'Enable','on');
            set(Yprmhist,'Enable','off');
        end
        if ~isempty(mArgsIn.curGraph)
            mArgsIn.Handles.DrawFcn(mArgsIn);
            figure(gcbf);
        end
    end
    
    function XaxisSelCh(hObject,eventdata)
        mArgsIn=guidata(hObject);
        hMainFig=mArgsIn.Handles.fh;
        
        mArgsIn.Display.Changed=1;
        mArgsIn.Display.graph_Xaxis=get(get(hObject,'SelectedObject'),'Tag');
        if get(Xauto,'Value')==1
            mArgsIn.Display.graph_Xaxis_param=get(get(hObject,'SelectedObject'),'UserData');
        end
        mArgsIn.Display.graph_Xaxis_Radio=find(get(hObject,'Children')==get(hObject,'SelectedObject'));
        guidata(hMainFig,mArgsIn);
        mArgsIn.Handles.DrawFcn(mArgsIn);
        figure(gcbf);
    end

    function YaxisSelCh(hObject,eventdata)
        mArgsIn=guidata(hObject);
        hMainFig=mArgsIn.Handles.fh;
        
        mArgsIn.Display.Changed=1;
        mArgsIn.Display.graph_Yaxis=get(get(hObject,'SelectedObject'),'Tag');
        if get(findobj(Xauto,'Value'))==1
            mArgsIn.Display.graph_Yaxis_param=get(get(hObject,'SelectedObject'),'UserData');
        end
        mArgsIn.Display.graph_Yaxis_Radio=find(get(hObject,'Children')==get(hObject,'SelectedObject'));
        guidata(hMainFig,mArgsIn);
        mArgsIn.Handles.DrawFcn(mArgsIn);
        figure(gcbf);
    end


    function XAutoCallback(hObject, eventdata)
        mArgsIn = guidata(hObject);
        mArgsIn.Display.Changed=1;
        if get(hObject,'Value')==1
            set(Xparam,'Enable','off');
            set(hObject,'Enable','on');
            mArgsIn.Display.graph_Xaxis_param=get(get(XaxisBG,'SelectedObject'),'UserData');
            mArgsIn.Display.XAuto=1;
        else
            set(Xparam,'Enable','on');
            for i=1:3
                if ~isnan(str2double(get(Xparam(i),'String')))
                    mArgsIn.Display.graph_Xaxis_param(i)=str2double(get(Xparam(i),'String'));
                end
            end
            mArgsIn.Display.XAuto=0;
        end
        guidata(mArgsIn.Handles.fh, mArgsIn);
        mArgsIn.Handles.DrawFcn(mArgsIn);
%         figure(gcbf);
    end
    
%     function XparamCallback(hObject,eventdata,hMainFig)
%         mArgsIn=guidata(hMainFig);
%         mArgsIn.Display.Changed=1;
%         Args=guidata(mArgsIn.Handles.graphprop);
%         for i=1:3
%             if ~isnan(str2double(get(Args.Xparam(i),'String')))
%                 mArgsIn.Display.graph_Xaxis_param(i)=str2double(get(Args.Xparam(i),'String'));
%             end
%         end
%         guidata(hMainFig,mArgsIn);
%         mArgsIn.Handles.DrawFcn(mArgsIn);
%         figure(gcbf);
%     end
%     function XAutoCallback(hObject,eventdata)
%         mArgsIn=guidata(hMainFig);
%         mArgsIn.Display.Changed=1;
%         if get(hObject,'Value')==1
%             set(get(get(hObject,'Parent'),'Children'),'Enable','off');
%             set(hObject,'Enable','on');
%             mArgsIn.Display.graph_Xaxis_param=get(get(Xaxis,'SelectedObject'),'UserData');
%             mArgsIn.Display.XAuto=1;
%         else
%             set(get(get(hObject,'Parent'),'Children'),'Enable','on');
%             for i=1:3
%                 if ~isnan(str2double(get(Args.Xparam(i),'String')))
%                     mArgsIn.Display.graph_Xaxis_param(i)=str2double(get(Args.Xparam(i),'String'));
%                 end
%             end
%             mArgsIn.Display.XAuto=0;
%         end
%         guidata(hMainFig,mArgsIn);
%         mArgsIn.Handles.DrawFcn(mArgsIn);
%         figure(gcbf);
%     end
%     function YprmhistCallback(hObject,eventdata)
%         mArgsIn=guidata(hMainFig);
%         mArgsIn.Display.Changed=1;
%         mArgsIn.Display.histnormalize=get(get(hObject,'SelectedObject'),'Tag');
%         guidata(hMainFig,mArgsIn);
%         mArgsIn.Handles.DrawFcn(mArgsIn);
%         figure(gcbf);
%     end
%     function YparamCallback(hObject,eventdata,hMainFig)
%         mArgsIn=guidata(hMainFig);
%         mArgsIn.Display.Changed=1;
%         Args=guidata(mArgsIn.Handles.graphprop);
%         for i=1:3
%             if ~isnan(str2double(get(Args.Yparam(i),'String')))
%                 mArgsIn.Display.graph_Yaxis_param(i)=str2double(get(Args.Yparam(i),'String'));
%             end
%         end
%         guidata(hMainFig,mArgsIn);
%         mArgsIn.Handles.DrawFcn(mArgsIn);
%         figure(gcbf);
%     end
%     function YAutoCallback(hObject,eventdata)
%         mArgsIn=guidata(hMainFig);
%         mArgsIn.Display.Changed=1;
%         if get(hObject,'Value')==1
%             set(get(get(hObject,'Parent'),'Children'),'Enable','off');
%             set(hObject,'Enable','on');
%             mArgsIn.Display.graph_Yaxis_param=get(get(Yaxis,'SelectedObject'),'UserData');
%             mArgsIn.Display.YAuto=1;
%         else
%             %            set(hObject,'Value',1);
%             set(get(get(hObject,'Parent'),'Children'),'Enable','on');
%             for i=1:3
%                 if ~isnan(str2double(get(Args.Yparam(i),'String')))
%                     mArgsIn.Display.graph_Yaxis_param(i)=str2double(get(Args.Yparam(i),'String'));
%                 end
%             end
%             mArgsIn.Display.YAuto=0;
%         end
%         guidata(hMainFig,mArgsIn);
%         mArgsIn.Handles.DrawFcn(mArgsIn);
%         figure(gcbf);
%     end
%     function SmoothCallback(hObject,eventdata)
%         mArgsIn=guidata(hMainFig);
%         mArgsIn.Display.smoothprm=str2double(get(hObject,'string'));
%         mArgsIn.Display.Changed=1;
%         guidata(hMainFig,mArgsIn);
%         mArgsIn.Handles.DrawFcn(mArgsIn);
%     end
end