function HelpKeys(~,~)
    h=figure('Position',[0,0,400,140],...
        'MenuBar','none',...
        'Name','EasyFlow Keyboard Shortcuts',...
        'NumberTitle','off',...
        'Visible','off');

    shortcut_keys={...
        'Ctrl-A',...
        'Ctrl-C',...
        ''};
    shortcut_desc={...
        'Rename graphs with sample name',...
        'Assign defult colors',...
        ''};

    hTitle=uicontrol(h,'Style','text',...
        'Position',[0,100,400,40],...
        'FontSize',20,...
        'FontWeight','bold',...
        'String',' Keyboard Shortcuts ');
    hKeys=uicontrol(h,'Style','text',...
        'Position',[0,0,90,100],...
        'FontSize',10,...
        'HorizontalAlignment','right',...
        'String',shortcut_keys);
    hDesc=uicontrol(h,'Style','text',...
        'Position',[110,0,300,100],...
        'FontSize',10,...
        'HorizontalAlignment','left',...
        'String',shortcut_desc);

    hspace=20;
    hKeys.Position(3)=hKeys.Extent(3);
    hDesc.Position(1)=hKeys.Position(1)+hKeys.Position(3)+hspace;
    hDesc.Position(3)=hDesc.Extent(3);
    hTitle.Position(3)=max(hTitle.Extent(3),hKeys.Extent(3)+hDesc.Extent(3)+hspace);
    h.Position(3)=hTitle.Position(3);
    movegui(h,'center');

    set(h,'Visible','on')

end